In [1]:
import pandas as pd
import sqlite3

In [2]:
cr = pd.read_csv("cr_products.csv")
bd = pd.read_csv("bd_products.csv")

In [3]:
cr.head()

                                                name category  price_pln
0                          Hamulce tarczowe SRAM DB8  hamulce     349.99
1  Hamulec tarczowy SHIMANO Deore BL-M4100 / BR-M...  hamulce     209.99
2  Hamulec tarczowy SHIMANO Deore BL-M6100 / BR-M...  hamulce     249.99
3  Hamulec tarczowy SHIMANO Deore BL-M6100 / BR-M...  hamulce     494.93
4  Hamulec tarczowy SHIMANO Deore BL-M6100 / BR-M...  hamulce     374.99

In [4]:
bd.head()

                                              name category  price_eur
0                Float Line Air Sleeve Rebuild Kit  dampery      26.99
1                       54mm Trunnion Service Tool  dampery      99.99
2      8x30 Rear Shock Bearing Adapter Socket Tool  dampery      28.99
3         Air Can Upgrade Kit Solo Air SIDLuxe A1+  dampery      29.99
4  Air Can XL Upgrade Kit Deluxe/ Super Deluxe C1+  dampery      54.99

In [5]:
cr.groupby('category').size()

category
hamulce        54
kasety         44
lancuchy       21
manetki        23
przerzutki     37
widelce       126
dtype: int64

In [6]:
bd.groupby('category').size()

category
dampery       108
hamulce        82
kasety         71
lancuchy       27
manetki       102
przerzutki     90
widelce       129
dtype: int64

In [7]:
cr_hamulce = cr[cr['category'] == 'hamulce']
cr_hamulce

                                                 name category  price_pln
0                           Hamulce tarczowe SRAM DB8  hamulce     349.99
1   Hamulec tarczowy SHIMANO Deore BL-M4100 / BR-M...  hamulce     209.99
2   Hamulec tarczowy SHIMANO Deore BL-M6100 / BR-M...  hamulce     249.99
3   Hamulec tarczowy SHIMANO Deore BL-M6100 / BR-M...  hamulce     494.93
4   Hamulec tarczowy SHIMANO Deore BL-M6100 / BR-M...  hamulce     374.99
5   Hamulec tarczowy SHIMANO Deore BL-MT501 / BR-M...  hamulce     209.99
6   Hamulec tarczowy SHIMANO Deore XT BL-M8100 / B...  hamulce     329.99
7   Hamulec tarczowy SHIMANO Deore XT BL-M8100 / B...  hamulce     702.98
8   Hamulec tarczowy SHIMANO Deore XT BL-M8100 / B...  hamulce     499.99
9   Hamulec tarczowy SHIMANO Deore XT BL-M8200/BR-...  hamulce     564.99
10  Hamulec tarczowy SHIMANO Deore XT BL-M8200/BR-...  hamulce     639.99
11   Hamulec tarczowy SHIMANO SLX BL-M7100 / BR-M7100  hamulce     279.99
12  Hamulec tarczowy SHIMANO SLX BL-M7100 / BR-M71...  hamulce     541.48
13   Hamulec tarczowy SHIMANO SLX BL-M7100 / BR-M7120  hamulce     369.99
14  Hamulec tarczowy SHIMANO SLX BL-M7100 / BR-M71...  hamulce     840.73
15   Hamulec tarczowy SHIMANO Saint BL-M820 / BR-M820  hamulce     609.99
16   Hamulec tarczowy SHIMANO XTR BL-M9100 / BR-M9100  hamulce     669.99
17  Hamulec tarczowy SHIMANO XTR BL-M9100 / BR-M91...  hamulce    1344.23
18   Hamulec tarczowy SHIMANO XTR BL-M9120 / BR-M9120  hamulce     829.99
19   Hamulec tarczowy SHIMANO XTR BL-M9200 / BR-M9200  hamulce     749.99
20   Hamulec tarczowy SHIMANO XTR BL-M9220 / BR-M9220  hamulce     869.99
21                          Hamulec tarczowy SRAM DB8  hamulce     189.99
22                      Hamulec tarczowy SRAM Guide R  hamulce     349.99
23                     Hamulec tarczowy SRAM Guide RS  hamulce     449.99
24                      Hamulec tarczowy SRAM Guide T  hamulce     299.99
25                   Hamulec tarczowy SRAM Maven Base  hamulce     599.99
26                 Hamulec tarczowy SRAM Maven Silver  hamulce     849.99
27               Hamulec tarczowy SRAM Maven Ultimate  hamulce     939.99
28             Tarcza hamulcowa SHIMANO Deore SM-RT64  hamulce      69.99
29         Tarcza hamulcowa SHIMANO Deore XT RT-MT800  hamulce     149.99
30          Tarcza hamulcowa SHIMANO Deore XT SM-RT81  hamulce     119.99
31          Tarcza hamulcowa SHIMANO Deore XT SM-RT86  hamulce     129.99
32         Tarcza hamulcowa SHIMANO Deore/SLX SM-RT66  hamulce      59.99
33   Tarcza hamulcowa SHIMANO Dura Ace / XTR RT-CL900  hamulce     214.99
34               Tarcza hamulcowa SHIMANO SLX SM-RT70  hamulce      69.99
35  Tarcza hamulcowa SHIMANO Ultegra / Deore XT RT...  hamulce     184.99
36              Tarcza hamulcowa SHIMANO XTR RT-MT900  hamulce     199.99
37   Zacisk hamulca tarczowego SHIMANO Deore BR-M6100  hamulce     124.99
38   Zacisk hamulca tarczowego SHIMANO Deore BR-M6120  hamulce     256.99
39   Zacisk hamulca tarczowego SHIMANO Deore BR-MT410  hamulce     147.99
40   Zacisk hamulca tarczowego SHIMANO Deore BR-MT420  hamulce     162.99
41   Zacisk hamulca tarczowego SHIMANO Deore BR-MT500  hamulce      95.99
42   Zacisk hamulca tarczowego SHIMANO Deore BR-MT520  hamulce     204.99
43  Zacisk hamulca tarczowego SHIMANO Deore XT BR-...  hamulce     174.99
44  Zacisk hamulca tarczowego SHIMANO Deore XT BR-...  hamulce     249.99
45  Zacisk hamulca tarczowego SHIMANO Deore XT BR-...  hamulce     299.99
46  Zacisk hamulca tarczowego SHIMANO Deore XT BR-...  hamulce     239.99
47  Zacisk hamulca tarczowego SHIMANO Deore XT BR-...  hamulce     319.99
48     Zacisk hamulca tarczowego SHIMANO SLX BR-M7100  hamulce     114.99
49     Zacisk hamulca tarczowego SHIMANO SLX BR-M7120  hamulce     269.99
50    Zacisk hamulca tarczowego SHIMANO Saint BR-M820  hamulce     414.99
51     Zacisk hamulca tarczowego SHIMANO XTR BR-M9120  hamulce     599.99
52     Zacisk hamulca tarczowego SHIMANO XTR BR-M9220  hamulce     529.99
53              Zacisk hamulca tarczowego SRAM DB8 A1  hamulce     219.99

In [9]:
bd_hamulce = bd[bd['category'] == 'hamulce']
bd_hamulce

                                                  name category  price_eur
108                             DB8 Stealth Disc Brake  hamulce      64.99
109                         DB8 Stealth Disc Brake Set  hamulce     159.99
110  DB8 Stealth Disc Brake Set + Centerline 180/200mm  hamulce     249.99
111  DEORE BL-M4100+BR-MT410 Scheibenbremsen-Set J-Kit  hamulce      44.98
112         DEORE BL-M4100+BR-MT420/410 Disc Brake Set  hamulce      99.99
..                                                 ...      ...        ...
185               XTR BL-M9220/BR-M9220 Disc Brake Set  hamulce     439.99
186       XTR BL-M9220/BR-M9220 Disc Brake Upgrade Kit  hamulce     448.99
187         XTR BL-M9220/BR-M9220/M9200 Disc Brake Set  hamulce     378.99
188             XTR BR-M9110 FM Disc Brake 1700mm rear  hamulce     169.99
189               XTR BR-M9120 Disc Brake 1000mm front  hamulce     168.99

[82 rows x 3 columns]

In [ ]:
hamulce = [
    {"cr_hamulce": "Hamulce tarczowe SRAM DB8", "bd_hamulce": "DB8 Stealth Disc Brake Set", "category": "hamulce"},
    {"cr_hamulce": "Hamulec tarczowy SHIMANO Deore BL-M4100 / BR-MT420", "bd_hamulce": "DEORE BL-M4100/BR-MT420 Disc Brake 1000mm front", "category": "hamulce"},
    {"cr_hamulce": "Hamulce tarczowe SRAM DB8", "bd_hamulce": "DB8 Stealth Disc Brake Set", "category": "hamulce"},
]