In [1]:
import pandas as pd
import sqlite3

In [2]:
cr = pd.read_csv("cr_products.csv")
bd = pd.read_csv("bd_products.csv")

In [3]:
cr.head()

                                         name category  price_pln
0         2x Hamulec tarczowy MAGURA MT SPORT  hamulce     341.98
1        Adapter do tarczy hamulcowej GALFER   hamulce      89.99
2       Adapter do tarczy hamulcowej SHIMANO   hamulce      59.99
3    Adapter do tarczy hamulcowej SWISS STOP   hamulce      74.99
4  Hamulce tarczowe MAGURA MT Trail SL Carbon  hamulce    1699.00

In [4]:
bd.head()

                                                name category  price_eur
0                  Float Line Air Sleeve Rebuild Kit  dampery      26.99
1     Rear Shock Piston Bolt Socket Tool Deluxe Nude  dampery      22.99
2                         54mm Trunnion Service Tool  dampery      99.99
3        8x30 Rear Shock Bearing Adapter Socket Tool  dampery      28.99
4  Air Can Basic Service Kit Monarch Plus/XX/RL/R...  dampery       9.99